server:
  port: 8080
  host: "0.0.0.0"

database:
  # Cloud PostgreSQL Service URI for staging
  service_uri: "${STAGING_DATABASE_URL}"
  
  # Connection pool settings for staging
  max_open_conns: 50
  max_idle_conns: 15
  conn_max_lifetime: 15 # minutes

redis:
  addr: "${STAGING_REDIS_URL}"
  password: "${STAGING_REDIS_PASSWORD}"
  db: 0

jwt:
  secret: "${STAGING_JWT_SECRET}"
  expiry_hours: 12

grpc:
  port: 9090
  host: "0.0.0.0"
